"use client";

import { useState } from "react";

import { analyticsService } from "@/services/analytics.service";
import type { InsightResponse } from "@/types/analytics";

type InsightsState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "success"; insight: InsightResponse };

export function AIInsightsPanel() {
  const [state, setState] = useState<InsightsState>({ status: "idle" });

  const handleGenerate = async () => {
    setState({ status: "loading" });

    try {
      const insight = await analyticsService.generateInsight({
        query:
          "Analyze current event analytics and provide business insights for leadership.",
      });
      setState({ status: "success", insight });
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : "Failed to generate AI insights";
      setState({ status: "error", message });
    }
  };

  return (
    <section className="dashboard-panel dashboard-insights">
      <div className="dashboard-panel-header">
        <div>
          <h2 className="dashboard-panel-title">AI Insights</h2>
          <p className="dashboard-muted">
            Gemini analyzes live summary data from PostgreSQL
          </p>
        </div>
        <button
          type="button"
          className="dashboard-button"
          onClick={handleGenerate}
          disabled={state.status === "loading"}
        >
          {state.status === "loading" ? "Generating…" : "Generate AI Insights"}
        </button>
      </div>

      {state.status === "idle" && (
        <p className="dashboard-muted">
          Click the button to generate data-driven business insights from your
          current analytics summary.
        </p>
      )}

      {state.status === "loading" && (
        <div className="dashboard-state dashboard-insights-state" role="status">
          <div className="dashboard-spinner" aria-hidden="true" />
          <p>Analyzing analytics data with Gemini…</p>
        </div>
      )}

      {state.status === "error" && (
        <div
          className="dashboard-state dashboard-state-error dashboard-insights-state"
          role="alert"
        >
          <p>{state.message}</p>
          <button
            type="button"
            className="dashboard-button"
            onClick={handleGenerate}
          >
            Retry
          </button>
        </div>
      )}

      {state.status === "success" && (
        <div className="dashboard-insights-result">
          <p className="dashboard-insights-model">
            Generated by {state.insight.model}
          </p>
          <div className="dashboard-insights-text">{state.insight.summary}</div>
        </div>
      )}
    </section>
  );
}
